import java.sql.ResultSet;
import java.util.HashMap;
import javax.swing.JOptionPane;
public class Employees extends javax.swing.JFrame {

    /**
     * Creates new form Transport_officer
     */
    public Employees() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_tousername = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_toname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_topass = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_tosalary = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField_cdate = new javax.swing.JTextField();
        jButton_addofficer = new javax.swing.JButton();
        jButton_searchofficer = new javax.swing.JButton();
        jButton_deleteofficer = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField_tgusername = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField_tgname = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField_tgpassword = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField_tgaddress = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField_tgcdate = new javax.swing.JTextField();
        jButton_addguide = new javax.swing.JButton();
        jButton_searchguide = new javax.swing.JButton();
        jButton_deleteguide = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton_exit = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Transport Officers"));

        jLabel5.setText("Username :");

        jLabel6.setText("Name :");

        jLabel7.setText("Password :");

        jTextField_topass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_topassActionPerformed(evt);
            }
        });

        jLabel8.setText("Salary :");

        jLabel9.setText("Contract Date :");

        jButton_addofficer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add-icon222.png"))); // NOI18N
        jButton_addofficer.setText("ADD");
        jButton_addofficer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addofficerActionPerformed(evt);
            }
        });

        jButton_searchofficer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search-icon2.png"))); // NOI18N
        jButton_searchofficer.setText("SEARCH");
        jButton_searchofficer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_searchofficerActionPerformed(evt);
            }
        });

        jButton_deleteofficer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete-icon222.png"))); // NOI18N
        jButton_deleteofficer.setText("DELETE");
        jButton_deleteofficer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteofficerActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh222.png"))); // NOI18N
        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/compupic22.png"))); // NOI18N
        jButton4.setText("View All");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton_addofficer, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_deleteofficer)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_cdate, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField_topass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                    .addComponent(jTextField_toname, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_tousername, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_tosalary))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_searchofficer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(13, 13, 13))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_tousername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_searchofficer, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_toname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_topass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_tosalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_cdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_deleteofficer)
                    .addComponent(jButton_addofficer)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Travel Guide"));
        jPanel3.setToolTipText("");

        jLabel10.setText("User Name :");

        jLabel11.setText("Name :");

        jLabel12.setText("Password :");

        jTextField_tgpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_tgpasswordActionPerformed(evt);
            }
        });

        jLabel13.setText("Address :");

        jLabel14.setText("Contract Date :");

        jButton_addguide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add-icon222.png"))); // NOI18N
        jButton_addguide.setText("ADD");
        jButton_addguide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addguideActionPerformed(evt);
            }
        });

        jButton_searchguide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search-icon2.png"))); // NOI18N
        jButton_searchguide.setText("SEARCH");
        jButton_searchguide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_searchguideActionPerformed(evt);
            }
        });

        jButton_deleteguide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete-icon222.png"))); // NOI18N
        jButton_deleteguide.setText("DELETE");
        jButton_deleteguide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteguideActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh222.png"))); // NOI18N
        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/compupic22.png"))); // NOI18N
        jButton5.setText("View All");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField_tgaddress)
                                .addComponent(jTextField_tgpassword)
                                .addComponent(jTextField_tgusername, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                .addComponent(jTextField_tgcdate))
                            .addComponent(jTextField_tgname, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_searchguide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton_addguide, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_deleteguide)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField_tgusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_searchguide, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jTextField_tgname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField_tgpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jTextField_tgaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField_tgcdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_addguide)
                    .addComponent(jButton_deleteguide)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sign-Back-icon2.png"))); // NOI18N
        jButton2.setText("back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Exit-the-2222.png"))); // NOI18N
        jButton_exit.setText("Exit");
        jButton_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_exitActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logout.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addComponent(jButton_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_addofficerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addofficerActionPerformed

        if (jTextField_toname.getText().isEmpty() && jTextField_tousername.getText().isEmpty() && jTextField_topass.getText().isEmpty() && jTextField_tosalary.getText().isEmpty() && jTextField_cdate.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Enter details to continue","Invalid Data",JOptionPane.ERROR_MESSAGE);
        }else
        {
            String username = jTextField_tousername.getText();
            String name = jTextField_toname.getText();
            String password = jTextField_topass.getText();
            String Salary = jTextField_tosalary.getText();
            String cDate = jTextField_cdate.getText();

            try {
                Database db = new Database();
                db.putdata("Insert into transportofficer values ('" + username + "','" + password + "','" + name + "','" + Salary + "','" + cDate + "')");
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jButton_addofficerActionPerformed

    private void jButton_searchofficerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_searchofficerActionPerformed

        if (jTextField_tousername.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Enter details to continue","Invalid Data",JOptionPane.ERROR_MESSAGE);
        }else
        {
            Database DB1 = new Database();

            ResultSet rset=DB1.GetInformation("Select * from transportofficer where username=('"+jTextField_tousername.getText()+"')");

            try {
                while ( rset.next() )
                {
                    jTextField_topass.setText(rset.getString("password"));
                    jTextField_toname.setText(rset.getString("name"));
                    jTextField_tosalary.setText(rset.getString("salary"));
                    jTextField_cdate.setText(rset.getString("employement_date"));
                }
            } catch (Exception e) {
            }
        }

    }//GEN-LAST:event_jButton_searchofficerActionPerformed

    private void jButton_deleteofficerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteofficerActionPerformed

        if (jTextField_tousername.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Enter details to continue","Invalid Data",JOptionPane.ERROR_MESSAGE);
        }else
        {
            try {
                Database DB1 = new Database();
                DB1.putdata("Delete from transportofficer where username='"+jTextField_tousername.getText()+"'");
            } catch (Exception e) {
            }
        }

    }//GEN-LAST:event_jButton_deleteofficerActionPerformed

    private void jButton_addguideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addguideActionPerformed

        if (jTextField_tgname.getText().isEmpty() && jTextField_tgusername.getText().isEmpty() && jTextField_tgpassword.getText().isEmpty() && jTextField_tgaddress.getText().isEmpty() && jTextField_tgcdate.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Enter details to continue","Invalid Data",JOptionPane.ERROR_MESSAGE);
        }else
        {
            String username = jTextField_tgusername.getText();
            String name = jTextField_tgname.getText();
            String password = jTextField_tgpassword.getText();
            String Address = jTextField_tgaddress.getText();
            String cDate = jTextField_tgcdate.getText();

            try {
                Database db = new Database();
                db.putdata("Insert into travelguide values ('" + username + "','" + password + "','" + name + "','" + Address + "','" + cDate + "')");
            } catch (Exception e) {
            }
        }

    }//GEN-LAST:event_jButton_addguideActionPerformed

    private void jButton_searchguideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_searchguideActionPerformed

        if (jTextField_tgusername.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Enter details to continue","Invalid Data",JOptionPane.ERROR_MESSAGE);
        }else
        {
            Database DB1 = new Database();

            ResultSet rset=DB1.GetInformation("Select * from travelguide where username=('"+jTextField_tgusername.getText()+"')");

            try {
                while ( rset.next() )
                {
                    jTextField_tgpassword.setText(rset.getString("password"));
                    jTextField_tgname.setText(rset.getString("name"));
                    jTextField_tgaddress.setText(rset.getString("address"));
                    jTextField_tgcdate.setText(rset.getString("contract_end_date"));
                }
            } catch (Exception e) {
            }
        }

    }//GEN-LAST:event_jButton_searchguideActionPerformed

    private void jButton_deleteguideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteguideActionPerformed

        if (jTextField_tgusername.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Enter details to continue","Invalid Data",JOptionPane.ERROR_MESSAGE);
        }else
        {
            try {
                Database DB1 = new Database();
                DB1.putdata("Delete from travelguide where username='"+jTextField_tgusername.getText()+"'");
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jButton_deleteguideActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextField_cdate.setText("");
    
    jTextField_tgaddress.setText("");
    jTextField_tgcdate.setText("");
    jTextField_tgname.setText("");
    jTextField_tgpassword.setText("");
    jTextField_tgusername.setText("");
    jTextField_toname.setText("");
    jTextField_topass.setText("");
    jTextField_tosalary.setText("");
    jTextField_tousername.setText("");
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Officer_menu TG = new Officer_menu();
        TG.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField_tgpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_tgpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_tgpasswordActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_exitActionPerformed

        this.dispose();

    }//GEN-LAST:event_jButton_exitActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
           try {
              HashMap param=new HashMap();
              MyiReportViewer viewer=new MyiReportViewer(".\\Oleada Cab Service\\src\\reports\\report5.jasper",param);
              viewer.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            HashMap param = new HashMap();
            MyiReportViewer viewer = new MyiReportViewer("C:\\Users\\ASUS USER\\Desktop\\Oleada Cab Service\\src\\reports\\report6.jasper", param);
            viewer.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField_topassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_topassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_topassActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
    transportofficerlogin TO = new  transportofficerlogin();
    TO.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton_addguide;
    private javax.swing.JButton jButton_addofficer;
    private javax.swing.JButton jButton_deleteguide;
    private javax.swing.JButton jButton_deleteofficer;
    private javax.swing.JButton jButton_exit;
    private javax.swing.JButton jButton_searchguide;
    private javax.swing.JButton jButton_searchofficer;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField_cdate;
    private javax.swing.JTextField jTextField_tgaddress;
    private javax.swing.JTextField jTextField_tgcdate;
    private javax.swing.JTextField jTextField_tgname;
    private javax.swing.JTextField jTextField_tgpassword;
    private javax.swing.JTextField jTextField_tgusername;
    private javax.swing.JTextField jTextField_toname;
    private javax.swing.JTextField jTextField_topass;
    private javax.swing.JTextField jTextField_tosalary;
    private javax.swing.JTextField jTextField_tousername;
    // End of variables declaration//GEN-END:variables
}
