
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import javax.print.attribute.standard.DateTimeAtCreation;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class reservationrequests extends javax.swing.JFrame {

    String user = null;
    /** Creates new form reservationrequests */
    public reservationrequests() {
        
        initComponents();
        
        String[] colName = { "Vehicle ID", "Travel Guide", "Start Date", "End Date","Approval", "Approved By" , "Approval Date" };
        DefaultTableModel contactTableModel = (DefaultTableModel) jTable1.getModel();
        contactTableModel.setColumnIdentifiers(colName);
        
        try {
        Database db = new Database();
        ResultSet rset = db.GetInformation("SELECT * FROM reserve");
        String[] result = new String[7];
        
        while(rset.next())
        {
            result[0] = rset.getString(1);
            result[1] = rset.getString(2);
            result[2] = rset.getString(3);
            result[3] = rset.getString(4);
            result[4] = rset.getString(5);
            result[5] = rset.getString(6);
            result[6] = rset.getString(7);
            contactTableModel.addRow(result);
        }
        
    } catch (Exception e) {
    }
    }
    
    public void transportofficer(String username){
       user = username;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton_back = new javax.swing.JButton();
        jButton_approve = new javax.swing.JButton();
        jButton_dissapprove = new javax.swing.JButton();
        jButton_exit2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reservation Requests");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sign-Back-icon2.png"))); // NOI18N
        jButton_back.setText("Back");
        jButton_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_backActionPerformed(evt);
            }
        });

        jButton_approve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/right22.png"))); // NOI18N
        jButton_approve.setText("Approve Selected");
        jButton_approve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_approveActionPerformed(evt);
            }
        });

        jButton_dissapprove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wrong22.png"))); // NOI18N
        jButton_dissapprove.setText("Desapprove Selected");
        jButton_dissapprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_dissapproveActionPerformed(evt);
            }
        });

        jButton_exit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Exit-the-2222.png"))); // NOI18N
        jButton_exit2.setText("Exit");
        jButton_exit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_exit2ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Documents-icon22.png"))); // NOI18N
        jButton1.setText("Reports");
        jButton1.setToolTipText("");
        jButton1.setIconTextGap(50);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_approve, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton_back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_exit2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_dissapprove, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_approve, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_dissapprove, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_back, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_exit2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(635, 658));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void jButton_approveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_approveActionPerformed

    int row = jTable1.getSelectedRow();
    String Vnum = jTable1.getValueAt(row,0).toString();
    String sDate = jTable1.getValueAt(row,2).toString();
    String eDate = jTable1.getValueAt(row,3).toString();
    Date date = Calendar.getInstance().getTime();
    DateFormat dformat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
    String currentDate = dformat.format(date);
    
    if (JOptionPane.showConfirmDialog(rootPane,"Are your sure to confirm the following reservation?","Confirm Submission",JOptionPane.OK_CANCEL_OPTION, WIDTH) == 0) 
    {
        try {
            
        } catch (Exception e) {
        }
        
        try {
            Database db = new Database();
            db.putdata("update reserve set isApproved = TRUE, approved_officer ='"+user+"', approved_date_time ='"+currentDate+"' where vehicle='"+Vnum+"' and from_date='"+sDate+"'and to_date='"+eDate+"'");
            
        } catch (Exception e)
        {
     
        }
    }
          reservationrequests resev2 = new reservationrequests();
    resev2.transportofficer(user);
    resev2.setVisible(true);
    this.dispose();  
}//GEN-LAST:event_jButton_approveActionPerformed

private void jButton_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_backActionPerformed

    Officer_menu TR = new Officer_menu();
    TR.setVisible(true);
    this.dispose();
}//GEN-LAST:event_jButton_backActionPerformed

private void jButton_dissapproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_dissapproveActionPerformed

    int row = jTable1.getSelectedRow();
    String Vnum = jTable1.getValueAt(row,0).toString();
    String sDate = jTable1.getValueAt(row,2).toString();
    String eDate = jTable1.getValueAt(row,3).toString();
    Date date = Calendar.getInstance().getTime();
    DateFormat dformat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
    String currentDate = dformat.format(date);
    
    if (JOptionPane.showConfirmDialog(rootPane,"Are your sure to confirm the following reservation?","Confirm Submission",JOptionPane.OK_CANCEL_OPTION, WIDTH) == 0) 
    {
        try {
            
        } catch (Exception e) {
        }
        
        try {
            Database db = new Database();
            db.putdata("update reserve set isApproved = FALSE, approved_officer ='"+user+"', approved_date_time ='"+currentDate+"' where vehicle='"+Vnum+"' and from_date='"+sDate+"'and to_date='"+eDate+"'");
            
        } catch (Exception e)
        {
            
        }
    }
          reservationrequests resev3 = new reservationrequests();
    resev3.transportofficer(user);
    resev3.setVisible(true);
    this.dispose();  
    
    
}//GEN-LAST:event_jButton_dissapproveActionPerformed

    private void jButton_exit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_exit2ActionPerformed
      this.dispose();
    }//GEN-LAST:event_jButton_exit2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          try {
              HashMap param=new HashMap();
              MyiReportViewer viewer=new MyiReportViewer("C:\\Users\\Kavinda\\Desktop\\reports\\report1.jasper",param);
              viewer.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reservationrequests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reservationrequests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reservationrequests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reservationrequests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new reservationrequests().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_approve;
    private javax.swing.JButton jButton_back;
    private javax.swing.JButton jButton_dissapprove;
    private javax.swing.JButton jButton_exit2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
